### ISSUE TITLE
CRUD topology template

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1501]
I have a database table with `topology_templates`. I'm currently trying to think about who can do what. Creating a `topology_template` seems like something a normal user might no be able to do but I'm no quite so sure about that. In order to remove clutter from the database we might only allow admin users to create, edit and remove `topology_templates`.

Editing a topology template comes with no hazard I guess if we're going to duplicate the topologies into the LES.

Deleting a topolog template also comes with no hazard.

@ChaelKruip @antw who would be able to create, update, destroy a topology template?

---

**TODO:**
- [ ] Creating a template should make it available to the `import` form. 
- [ ] Duplicate a `topology_template` into a `topology` when importing.
- [ ] Make it possible to create a `topology_template`
- [ ] Make it possible to update a `topology_template`
- [ ] Make it possible to delete a `topology_template`
