### ISSUE TITLE
Checklist: open tasks sprint 2 gas

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#655]
To help us keep track of progress and priorities in the final stretch :smile: 
This is a living document, @antw @grdw please update, link issues and ask for clarification etc.

The following features/tasks still need some work from @antw (ordered roughly by priority):

- [x] Financial measures for gas (consumption, production and number of connections)
- [x] Strategy for hybrid heat pumps (switch to gas if network is congested)
- [x] Show load of gas in load chart
- [x] Demand-scaled behaviour for heat and hot water (https://github.com/quintel/etmoses/issues/577)
- [x] HHP should switch to gas if 'binary' profile says so (back-end)
- [x] ~~Subnet awareness~~

The following features/tasks still need some work from @grdw  (ordered roughly by priority):

- [x] Issues with new technology matrix (https://github.com/quintel/etmoses/pull/646#issuecomment-163016540)
- [x] Issues with business cases (https://github.com/quintel/etmoses/issues/653)
- [x] HHP should switch to gas if 'binary' profile says so (front-end/database)
- [x] Proper redirect to original url (#587)

The following features/tasks still need some work from @JeroenvdLogt   (ordered roughly by priority):

- [ ] Document the cost of gas connections (https://github.com/quintel/etmoses/issues/654) 

The following features/tasks still need some work from @chaelkruip  (ordered roughly by priority):

- [x] Upload new space heating profiles
- [x] Upload temperature profile
- [ ] Add documentation on EV profiles

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers

**Comment by grdw** [comment]
#691
