### ISSUE TITLE
OVERVIEW TICKET: heat networks

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#862]
This ticket serves as an overview for Sprint 3 about heat networks. It contains links to main issues about this topic.

## Background

Heat networks are the third infrastructure to be added to ETMoses (after electricity and gas). 

- [x] High-over explanation of how the sources feed the network: https://github.com/quintel/etmoses/issues/963

## Topology

- [x] Interface for primary and secondary infrastructure: https://github.com/quintel/etmoses/issues/1049
- [x] How to include the cost of primary infrastructure for heat networks: https://github.com/quintel/etmoses/issues/962
- [x] How to include the cost of secondary infrastructure for heat networks: https://github.com/quintel/etmoses/issues/966

## Modeling

We are modelling the network energetically (kW and kWh). Temperature is not modelled explicitly. 

- [x] Explanation of how the heat network works energetically: https://github.com/quintel/etmoses/issues/971
- [ ] How losses are being dealt with: https://github.com/quintel/etmoses/issues/972

## Sources

- [x] How the sources will be imported into ETMoses: https://github.com/quintel/etmoses/issues/967
- [x] How the sources will be shown and edited: https://github.com/quintel/etmoses/issues/968
- [x] A generic source should be added: https://github.com/quintel/etmoses/issues/1014
- [x] marginal costs should be improved: https://github.com/quintel/etmoses/issues/1036

## Relation to existing infrastructure (e.g., electricity topology)

- [x] How to count the number of connections: https://github.com/quintel/etmoses/issues/970
- [x] How connections of the heat network are associated with the topology: https://github.com/quintel/etmoses/issues/973

## Costs

- [x] Measures need to be added to Market Models: https://github.com/quintel/etmoses/issues/1051
- [x] Costs of primary (transmission) infrastructure: https://github.com/quintel/etmoses/issues/962
- [x] Costs of secondary (distribution) infrastructure: https://github.com/quintel/etmoses/issues/966
- [x] Costs of central production units: https://github.com/quintel/etmoses/issues/1018

Some rules of thumb can be found in [this ticket](https://github.com/quintel/etmoses/issues/886)

## Visualisation

For end-points the demand for heat and the different forms of supply need to be shown per time-step (similar to gas and electricity).

- [x] Load charts for heat: https://github.com/quintel/etmoses/issues/964

**Comment by ChaelKruip** [comment]
# Links to issues

- [ ] Load charts for heat: https://github.com/quintel/etmoses/issues/964

**Comment by Sanne512** [comment]
I was wondering when the heat networks will be working on the Beta server? Because I can adjust the settings (jeeeeej), but I can't view the heat load.

**Comment by ChaelKruip** [comment]
> I was wondering when the heat networks will be working on the Beta server? Because I can adjust the settings (jeeeeej), but I can't view the heat load.

The chart is on BETA!:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/16561469/a7a9d42a-41f9-11e6-9207-6854204bac03.png)

I have already posted several possible improvements [here](https://github.com/quintel/etmoses/issues/1161). You can add your possible issues to that ticket @Sanne512

**Comment by Sanne512** [comment]
When will heat infrastructure be available on the pro server?

**Comment by ChaelKruip** [comment]
> When will heat infrastructure be available on the pro server?

If we all feel that the BETA server is stable enough, we can deploy the new functionality to the LIVE server. It is more risky and difficult to deploy only a certain feature (such as the heat infra). My suggestion would be to work on stability and bugs on BETA for the remainder of the sprint and then deploy to LIVE (end of August). @Sanne512 do you have preference for any other time-frame?

**Comment by Sanne512** [comment]
That sounds fine by me. @ThomBuijs and @JeroenvdLogt could you give an indication when you would need the heat infrastructure for your use cases?

**Comment by ThomBuijs** [comment]
Preferably I would need it next week, since then I will start a new use case which would need the heat infrastructure. I don't know if it is a possibility to start working on electricity and gas and as soon as the heat infrastructure is on the pro I could impelement this as well in my LES or if I have to create a new LES. This would give me and you some extra time. If it is not feasible to deploy the heat infrastructure before the end of August on the pro server, then I can wait.

**Comment by Sanne512** [comment]
@ChaelKruip Could you answer @ThomBuijs 's question above? 

I'm including @MarjoleinSchwachofer

**Comment by ChaelKruip** [comment]
> I don't know if it is a possibility to start working on electricity and gas and as soon as the heat infrastructure is on the pro I could impelement this as well in my LES or if I have to create a new LES.

This is possible but @antw or @grdw will have to manually add heat infrastructure to your LES once it becomes available on the LIVE server.

> If it is not feasible to deploy the heat infrastructure before the end of August on the pro server, then I can wait.

I think it would be a better to keep working on the issues that we are still having with the heat network (e.g., https://github.com/quintel/etmoses/issues/1319, https://github.com/quintel/etmoses/issues/1310, https://github.com/quintel/etmoses/issues/1261, https://github.com/quintel/etmoses/issues/1161, https://github.com/quintel/etmoses/issues/1079, https://github.com/quintel/etmoses/issues/1097) and only after extensive testing put heat network functionality on the LIVE server. This will likely take the rest of the sprint.

@ThomBuijs please contact me directly if this creates issues with your deadlines and I can advise you about a temporary work-around.

**Comment by ChaelKruip** [comment]
Closing as this issue has been resolved.
